spring:
  config:
    activate:
      on-profile: dev
    import: application.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PW_DEV}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST_DEV}
      repositories:
        enabled: false
